CC = gcc -g -O
RM = rm -f
OEXT = .o
EEXT =
SLEXT = .a
AR = ar rcs
TARGET=testlibfun

all: libfun$(SLEXT) $(TARGET)$(EEXT)

$(TARGET)$(OEXT):

$(TARGET)$(EEXT): libfun$(SLEXT)

functions$(OEXT): functions.c
	$(CC) -c functions.c

libfun$(SLEXT): functions$(OEXT)
	$(AR) libfun.a functions$(OEXT)

clean:
	$(RM) libfun$(SLEXT) functions$(OEXT) $(TARGET)$(EEXT)

.PHONY: clean

